### ISSUE TITLE
Event declarations in solidity examples should follow CamelCase convention

### ISSUE THREAD

**Issue by bonedaddy** [provable-things/docs#14]
As per the solidity documentation, function names should follow snakeCase notation, and event names should follow CamelCase notation in solidity code. In the 'Quick Start' section of the documentation, the event names should be updated to make it easy for the reader to easily distinguish function calls from event calls.

**Comment by D-Nice** [comment]
Thanks, we'll look to update this before the end of the weekend, or let us know if you wish to make appropriate PR.

**Comment by bonedaddy** [comment]
Under normal circumstances I would LOVE to submit  a PR but unfortunately I'm in Hawaii this week!

**Comment by D-Nice** [comment]
Should be fixed as of https://github.com/oraclize/docs/commit/f9c6c3cabe773e7c757752e9c43641a5e23cd301

**Comment by 4ntoine** [comment]
Sorry, where it comes from?
> event names should follow CamelCase notation

**Comment by D-Nice** [comment]
@4ntoine https://solidity.readthedocs.io/en/v0.4.24/style-guide.html#event-names

**Comment by 4ntoine** [comment]
@D-Nice Thanks for pointing out
