### ISSUE TITLE
Many grammar errors and typos in May 2018 version of the documentation

### ISSUE THREAD

**Issue by vitoc** [provable-things/docs#17]
This isn't too serious but thought I'll place a few notes here anyway as it does affect the perceived quality of the documentation (and the service):

- This **solutions** elegantly solves the Oracle Problem:
 
- While building the service, the Oraclize team has realized that the concept of authenticity proofs has much broader applicability **that** initially envisioned.

- A query is an array of parameters which needs **to evaluated** in order to complete a specific data source type request: query: [ parameter_1, parameters_2, ...];
	
- Oraclize recommends **to discards** the result and create a new query. 

These were spotted in the 31st May 2018 version of the documentation.

**Comment by D-Nice** [comment]
Thanks for reviewing and bringing it up. We'll see to get theses issues fixed for the next documentation update!

**Comment by bertani** [comment]
Closing, as this has been fixed [here](https://github.com/oraclize/docs/commit/62d6c4e6cf0c1a9f9531e08dda1db73893b902d1)
