### ISSUE TITLE
Proofreading Oraclize Docs

### ISSUE THREAD

**Issue by rmerom** [provable-things/docs#4]
Hi, just a couple of suggestions, feel free to ignore:

> This means that the datasources don’t need to adapt or understand the blockchain and they can keep providing their data via the channels they already have (tipically their own Web APIs).

Tipically is spelled typically.

> While this could be seen as a weakness, it really doesn’t. 
It really isn't.

**Comment by bertani** [comment]
Thanks, just fixed!
